version: "3"
services:
  app:
    build: .
    container_name: nest_app
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=nest_user
      - DATABASE_PASSWORD=nest_password
      - DATABASE_NAME=nest_db
    ports:
      - "3000:3000"
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5434:80"
volumes:
  db_data:
